### ISSUE TITLE
Plan to support Firefox?

### ISSUE THREAD

**Issue by antfu** [zikaari/crx-bridge#4] opened 2020-05-17 12:38 UTC
Thanks so much for this tool! It's awesome and saves me a lot of time.

I am trying to develop extensions cross-browsers.

With [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) we can have a single entry for different browsers(Chrome, Firefox, Opera). For example

```js
import browser from 'webextension-polyfill'

browser.runtime.sendMessage(...)

// will become this in Chrome:
// chrome.runtime.sendMessage(...)

// will become this in Firefox:
// firefox.runtime.sendMessage(...)
```

Wondering if you are interested in supporting this feature. I would also love to make PR.

Thanks :)

**Comment by NeekSandhu** [comment] 2020-05-17 12:41
I like the idea. Please create a PR and we can that going.

**Comment by smeijer** [comment] 2020-07-01 19:09
@antfu, did you take a look at the implementation? I would love to have this lib to support other browsers as well (Firefox / Edge)

**Comment by antfu** [comment] 2020-07-01 19:12
@smeijer I want to but I haven't got time to do it. Please feel free and go ahead for your implementation, I happy to do some help with it as well :)

**Comment by NeekSandhu** [comment] 2020-07-01 23:59
I can invest myself into this since I see this library has been gaining traction across multiple projects (and some of my own projects could use the enhancement).

Do you think it'd make sense to deprecate this package in favor of a new package with exact same API but a different name? or would it be better to add ff/edge support to the current package? Wondering because `crx` in the name `crx-bridge` stands for chrome extension.

I've been thinking `webext-bridge`, but it doesn't sound half as cool as `crx-bridge` 😅

@jgillick you're also welcome to add your opinion around the potential restructuring.

**Comment by smeijer** [comment] 2020-07-02 08:33
I think `crx-bridge` works fine for cross-browser support. I didn't make the connection `crx -> chrome` before you mentioned it. And besides, even if one makes it, the other browsers also have a global `chrome` property for compatibility reasons (firefox) or because they build on the same code base (edge).

If it's about visibility, I think the readme should just mention the cross-browser compatibility clearly. Most packages are found by googling for terms or searching npm.

If you're going for a different name, I would vote to include something like `message` or `msg` in it. That is what I as a first-time extension builder was looking for. Something that "send messages from extension to page".

Or how about `isomorphic-postmessage`? `isomorphic-fetch` is the `fetch` for `node + browser`, `isomorphic-postmessage` could be the `postMessage` for `window + extension`.

I'm not sure if that name would be technically correct, but it does have a nice ring to it.

If this extension works between `window` and `iframe` (haven't tried), then it could even attract a new target audience, as it is then positioned as "better postMessage"

**Comment by NeekSandhu** [comment] 2020-07-08 01:07
For now, I'll just push the ff/edge support to `crx-bridge`. we can change the name later if we feel like it.

ETA: ~13 Jul 2020

**Comment by NeekSandhu** [comment] 2020-07-16 09:14
Delivery update:

I've decided to ship the next release along with proper testing to ensure safety for all of us. And I mean tests with "real" chrome as opposed to mocks and fixtures. Puppeteer is indeed very cool ;) 

Testing for messaging between content scripts and background page was easy. The delay is caused by me also trying to include devtools messaging in the mix, I firmly believe that it'll work, I'll keep trying till the end of this week, if it works, awesome, otherwise I'll release it with what I have so far.

**Comment by smeijer** [comment] 2020-10-13 08:31
@NeekSandhu, did you find something that blocked the release?

**Comment by NeekSandhu** [comment] 2020-10-14 09:00
Ah snap! apologies guys, a bunch of stuff had me upside down for the past few weeks.

Anyway, things are back to normal, version `3.0.0` is now live, please run `yarn add crx-bridge` again to get the latest version.

Feel free to review the patch [here](https://github.com/NeekSandhu/crx-bridge/commit/724f538f228a7b2022d41204305d2dcf5627d61d).

I've tested on Chrome _(content-script <-> background <-> devtools)_ and Firefox _(content-script <-> background)_, couldn't test devtools integration with Firefox, but I'm confident that it should work no probs.

**Comment by NeekSandhu** [comment] 2020-10-21 05:08
Once you guys feel comfortable using the new version and have tested it for a few days, drop a like on this comment if you find it's satisfactory. I'll check back after 2 weeks and I'll close the issue if there are ~3 likes.

**Closed** 2022-06-29 00:18 UTC
Labels: delivered
